# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ devel ]
    paths-ignore:
      - 'resources/**'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches: [ devel ]
    paths-ignore:
      - 'resources/**'
      - 'LICENSE'
      - '**.md'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - 
      name: 'Checkout' 
      uses: actions/checkout@v3
     
     - 
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'

     - 
      name: 'Install steam lib'
      run: nimble install -y

     -
      name: 'Generate docs' 
      run: nimble docs
     
     -
      name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
